### ISSUE TITLE
VSCode installation error / issues on Windows

### ISSUE THREAD

**Issue by leouk** [overturetool/vdm-vscode#194]
Hi folks, 

When trying to install on Windows, some users are getting the log below. VSCode "works" in other ways, but not to install VDM-VSCode extension. Any clues/hints on what's happening?

Here is the log: 
2022-11-16 10:20:52.031 [error] Unable to resolve nonexistent file 'c:\Program Files\Microsoft VS Code\resources\app\extensions': Error: Unable to resolve nonexistent file 'c:\Program Files\Microsoft VS Code\resources\app\extensions'
    at c.resolve (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:37:19164)
    at async k.scanExtensionsFromLocation (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:115317)
    at async k.scanExtensions (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:115001)
    at async C.scanDefaultSystemExtensions (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:111876)
    at async Promise.all (index 0)
    at async C.scanSystemExtensions (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:107812)
    at async Promise.all (index 0)
    at async C.scanAllExtensions (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:107410)
    at async G.scanExtensions (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:190456)
    at async $.getAllDepsAndPackExtensions (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:94116)
    at async $.installExtension (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:89038)
    at async $.installFromGallery (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:86873)

**Comment by idhugoid** [comment]
Not reproducible in a Windows machine, but need all the specs for the problem to be sure. Meanwhile and looking at some of your screenshots in https://github.com/overturetool/vdm-vscode/issues/160 there is a possible workaround to try out... Can you try to reinstall by making sure your antivirus is not meddling with the installed files?
